Add basic dns utilities for SRV record support in Mindustry (#116)
* dns utilities

* namin' + jndi over resolv

* another naming error

* use wayzer solution, well known dns servers

* do not continue lookup on empty results

* catch Throwable instead of NoClassDefFoundError in jndi nameserver provider